//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        internal int ClientID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string MailAddress { get; set; }
        public string CellPhoneNo { get; set; }
        public string TelephoneNo { get; set; }
    }
}
