//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccountBalance
    {
        public int ClientID { internal get; set; }
        public int CurrencyID { internal get; set; }
        public Nullable<int> rawAmount { internal get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
