//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccountBalance
    {
        internal int ClientID { get; set; }
        internal int CurrencyID { get; set; }
        internal Nullable<int> rawAmount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
